import {
	Container,
	Heading,
	Spinner,
	Table,
	Tbody,
	Td,
	Th,
	Thead,
	Tr,
} from '@chakra-ui/react';
import Head from 'next/head';
import { useEffect } from 'react';
import { useProducts } from '@/features/product/useProduct';

// chakra -> ui CSS framework
// formik -> handle form
// yup -> validation
// axios -> http request (API calls)
// react-query -> manage API calls

export default function Home() {
	const {} = useProducts();

	const renderProducts = () => {
		return products.map((product) => {
			return (
				<Tr key={product.id.toString()}>
					<Td>{product.id}</Td>
					<Td>{product.title}</Td>
					<Td>{product.price}</Td>
					<Td>{product.description}</Td>
					<Td>{product.image}</Td>
				</Tr>
			);
		});
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Container>
					<Heading>Product page</Heading>
					<Table>
						<Thead>
							<Tr>
								<Th>ID</Th>
								<Th>Title</Th>
								<Th>price</Th>
								<Th>description</Th>
								<Th>image</Th>
							</Tr>
						</Thead>
						<Tbody>
							{renderProducts()}
							{isLoading ? <Spinner /> : null}
						</Tbody>
					</Table>
				</Container>
			</main>
		</>
	);
}
